/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mariuszbeltowski' at '4/23/16 12:17 PM' with Gradle 2.12
 *
 * @author mariuszbeltowski, @date 4/23/16 12:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
